apiVersion: v1
kind: Service
metadata:
  name:  fraud-detect-api-service
spec:
  selector:
    app:  fraud-detect-api
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fraud-detect-api
spec:
  selector:
    matchLabels:
      app:  fraud-detect-api
  replicas: 4
  template:
    metadata:
      labels:
        app:  fraud-detect-api
    spec:
      containers:
      - name:  fraud-detect-api
        image:  fraud-detect-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000